version: "3"

services:
    sportsstore:
        build:
            context: .
            dockerfile: Dockerfile
        environment:
            - ConnectionStrings:SportsStoreConnection=Server=sqlserver;Database=SportsStoreDB;User=sa;Password=SAPassWORD@50;
            - ConnectionStrings:IdentityConnection=Server=sqlserver;Database=IdentityDB;User=sa;Password=SAPassWORD@50;
        image: sportsstore
        container_name: sportsstore
        depends_on:
            - sqlserver
        networks:
            - network
        ports:
            - "5000:5000"
    sqlserver:
        image: microsoft/mssql-server-linux
        container_name: sqlserver
        environment:
            SA_PASSWORD: "SAPassWORD@50"
            ACCEPT_EULA: "Y"
        networks:
            - network
        ports:
            - "1433:1433"
networks:
    network: